version: "2"
services:
  faq-service-daemon:
    restart: always
    image: kirikovr/skbt:latest
    network_mode: host
    volumes:
      - ./logs:/app/logs
      - ./config-local.json:/app/config-local.json