version: "2"
services:
  skbt:
    restart: always
    image: kirikovr/skbt:latest
    network_mode: host
    volumes:
      - ./logs:/app/logs
      - ./config-local.json:/app/config-local.json

  migration:
    restart: on-failure
    image: kirikovr/skbt-migration:latest
    network_mode: host

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: psql-skbt
    ports:
      - 5431:5432